### ISSUE TITLE
How to generate thumbnail for a pdf?

### ISSUE THREAD

**Issue by rlingineni** [FelixSchwarz/anythumbnailer#3]
Hi,

I am trying to use this library, however, I am unable to understand to how I can use it.  I am trying to generate a thumbnail for a PDF.

I am not sure if I am doing it correctly 
```
from anythumbnailer import create_thumbnail
output_buffer = create_thumbnail("sample.pdf")

with io.open('sample.png', 'w') as file:
    file.write(output_buffer)
```

I do not think my usage is right. I'm new to python, as well as this library. Is it possible you could let me know how to successfully perform this coversion?

**Comment by FelixSchwarz** [comment]
Your example looks almost ok besides some minor Python issues:

    with open('sample.jpg', 'wb') as file:
        file.write(output_buffer.read())

In detail:
- thumbnails are written as "jpg" files
- just use `open()` instead of `io.open()` (though `io.open()` should work as well if you import `io`)
- open file in "binary mode" ("wb")
- "output_buffer" is a BytesIO instance (file-like)

You can try using the updated file writing but I suspect another problem earlier: One of the bigger rough edges of this library is that it is that thumbnailer paths are hard-coded and a thumbnailer is just not available if one of the executables is missing.

For pdf2jpg you need '/usr/bin/pdftoppm', '/usr/bin/pnmtopng', '/usr/bin/pnmtojpeg'. On Fedora the packages for that are `poppler-utils` and `netpbm-progs`.

Feel free to reopen if this does not solve your problem. I'm happy to help :-)
